modLoader="javafml"
loaderVersion="[3,)"
license="MIT"

[[mods]]
modId="lavaflow"
version="0.1.0-SNAPSHOT"
displayName="LavaFlow"
authors="BZLZHH"
description='''
Vulkan 1.1 backend for Minecraft Blaze3D.
'''

[[mixins]]
config="lavaflow.mixins.json"

[[mixins]]
config="lavaflow-sodium.mixins.json"

[[dependencies.lavaflow]]
modId="neoforge"
type="required"
versionRange="[26.2.0.32-beta,)"
ordering="NONE"
side="CLIENT"

[[dependencies.lavaflow]]
modId="minecraft"
type="required"
versionRange="[26.2,26.3)"
ordering="NONE"
side="CLIENT"
